# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"toPIL": "01_preprocess.ipynb",
         "color_to_gray": "01_preprocess.ipynb",
         "gray_to_bw": "01_preprocess.ipynb",
         "is_bw": "01_preprocess.ipynb",
         "contourFilter": "01_preprocess.ipynb",
         "drawContour": "01_preprocess.ipynb",
         "bw_to_contours": "01_preprocess.ipynb",
         "draw_hough_lines": "01_preprocess.ipynb",
         "draw_hough_linesp": "01_preprocess.ipynb",
         "contour_to_hough": "01_preprocess.ipynb",
         "Lines": "01_preprocess.ipynb",
         "Coord": "03-piece-classifier.ipynb",
         "CropBox": "03-piece-classifier.ipynb",
         "Color": "03-piece-classifier.ipynb",
         "Piece": "03-piece-classifier.ipynb",
         "BoardImage": "03-piece-classifier.ipynb",
         "get_coord": "03-piece-classifier.ipynb"}

modules = ["image.py",
           "classifier.py",
           "None.py"]

doc_url = "https://idrisr.github.io/chessocr/"

git_url = "https://github.com/idrisr/chessocr/tree/master/"

def custom_doc_links(name): return None
