# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/05_hough.py.ipynb (unless otherwise specified).

__all__ = ['Hough']

# Cell
import numpy as np
import pandas as pd
from PIL import Image
import PIL

# Cell
class Hough:
    """ takes a contoured image and calculates the horizontal and vertical lines based on the hough transform """

    def __init__(self, img):
        """ img must be binarized image of contours """
        assert is_bw(img), "Image must be binarized"
        self.img = img
        self.a = np.array(self.img)

    @property
    def hsig(self):
        """ signal for horizontal lines"""
        return self.a.sum(axis=0)

    @property
    def vsig(self):
        """ signal for vertical lines"""
        return self.a.sum(axis=1)

    def show(self):
        fig = plt.figure(figsize=(8, 4))
        gs = fig.add_gridspec(1, 2)
        ax1 = fig.add_subplot(gs[0, 0])
        ax1.plot(self.hsig.ravel())
        ax1.set_title('horizontal')
        ax2 = fig.add_subplot(gs[0, 1])
        ax2.plot(self.vsig.ravel())
        ax2.set_title('vertical')